{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trading-simulator.fullname" . }}-backend
  labels:
    {{- include "trading-simulator.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "trading-simulator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- end }}
