{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "trading-simulator.fullname" . }}
  labels:
    {{- include "trading-simulator.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.paths.backendApi }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "trading-simulator.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: {{ .Values.ingress.paths.frontend }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "trading-simulator.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
