apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trading-simulator.fullname" . }}-db
  labels:
    {{- include "trading-simulator.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.internalDatabase.credentials.mysqlRootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.internalDatabase.credentials.mysqlDatabase | quote }}
  MYSQL_USER: {{ .Values.internalDatabase.credentials.mysqlUser | quote }}
  MYSQL_PASSWORD: {{ .Values.internalDatabase.credentials.mysqlPassword | quote }}
